version: "3.9"

services:

  # PostgreSQL database service
  postgres:
    image: postgres:15-alpine
    container_name: n8n-postgres-simple-node ##Optional: If you want to start another container without deleting the existing one, change the name
    restart: unless-stopped
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # persistent database data
    networks:
      - n8n-network

  # n8n automation service
  n8n:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: n8n-simple-node
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Database configuration
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n

      # Custom nodes path
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom

      # Security settings
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "admin"
      NODE_ENV: "production"
      N8N_HOST: "localhost"
      N8N_PORT: 5678

      # Execution and timezone settings
      EXECUTIONS_PROCESS: "main"
      GENERIC_TIMEZONE: "UTC"

    volumes:
      - ./n8n_data:/home/node/.n8n             # persistent workflows, credentials, and settings
      - ./dist/TrueNumberGeneratorNode:/home/node/.n8n/custom  # compiled custom nodes

    depends_on:
      - postgres
    networks:
      - n8n-network
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

networks:
  n8n-network:
    driver: bridge
